// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by the extension VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Lighthouse2
{
    internal sealed partial class Vsix
    {
        public const string Id = "Lighthouse2.4b62eb00-6ee8-4808-bb29-de3102a042ac";
        public const string Name = "Lighthouse2";
        public const string Description = @"Empty VSIX Project.";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Dax Pandhi";
        public const string Tags = "";
    }
}
