// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Lighthouse2
{
    internal sealed partial class Vsix
    {
        public const string Id = "Lighthouse2.4b62eb00-6ee8-4808-bb29-de3102a042ac";
        public const string Name = "Lighthouse";
        public const string Description = @"Empty VSIX Project.";
        public const string Language = "en-US";
        public const string Version = "2.0.0.1";
        public const string Author = "QuadSpinner";
        public const string Tags = "C#,Highlighting,Productivity";
    }
}
